### ISSUE TITLE
scroll handler should be run on init

### ISSUE THREAD

**Issue by ffuubarbuzz** [AurelioDeRosa/audero-sticky#17]
Otherwise items that should be in fixed position from the very beginning get it only on first scroll handler call. [demo](https://jsfiddle.net/Paul_Kozlovitch/6othgv3a/1/)

**Comment by AurelioDeRosa** [comment]
Thank you for reporting this issue too. I've fixed it and it'll be included in version 0.3.1.

On a side note, I've seen that you're quite active in reporting issues for this polyfill. Would you be interested in collaborating?

**Comment by ffuubarbuzz** [comment]
@AurelioDeRosa Sorry for such a long silence, I've been through many big changes in my life. I reported actively because I used your polyfill in few projects on my previous job, which is not the case now. Anyway, I find it very useful and well-made so I'd like to be helpful to the best of my abilities, which (time and skill) I'm not very confident about.
