### ISSUE TITLE
typo in readme

### ISSUE THREAD

**Issue by ffuubarbuzz** [AurelioDeRosa/audero-sticky#2]
I believe you've lost a `.` in selector the last example:

```
if (!Sticky.isFeatureSupported()) {
   Sticky.autoInit({
      selector: 'fixedsticky'
   });
}
```

**Comment by ffuubarbuzz** [comment]
Also `autoinit([options])` [here](https://github.com/AurelioDeRosa/audero-sticky#stickyautoinitoptions) probably should be `autoInit([options])`

**Comment by AurelioDeRosa** [comment]
Thank you for opening this issue. The typos have been fixed.

**Comment by ffuubarbuzz** [comment]
Thank you for fast fix!
