### ISSUE TITLE
options not respected in autoInit

### ISSUE THREAD

**Issue by ffuubarbuzz** [AurelioDeRosa/audero-sticky#3]
I'm trying example from readme

```
if (!Sticky.isFeatureSupported()) {
   Sticky.autoInit({
      selector: 'fixedsticky'
   });
}
```

Sticky element always gets `z-index: 0`, though original element has `z-index: 10` cause `getZIndex()` is always passed default `.sticky` as a selector. I suppose this happens because you're not passing `options` to the `Sticky()` here:
https://github.com/AurelioDeRosa/audero-sticky/blob/master/src/audero-sticky.js#L324

**Comment by AurelioDeRosa** [comment]
Thank you for reporting this issue. It has been fixed.
