### ISSUE TITLE
opposite margin is not respected

### ISSUE THREAD

**Issue by ffuubarbuzz** [AurelioDeRosa/audero-sticky#6]
If set, for example, element's styles

```
position: sticky;
top: 0;
margin-bottom: 100px;
```

it should not be able to overlap this 100px bottom gap being in fixed position. You can compare polyfill with native behavior in FF, Safari: http://codepen.io/ThiRaBrTNK/pen/gPjVyy

**Comment by AurelioDeRosa** [comment]
The issue is fixed and it'll be available in the next release. Thank you for the feedback.

**Comment by ffuubarbuzz** [comment]
Man, you are doing fantastic job! Thank you so much!
